#ifndef __CUSPARSE_H__
#define __CUSPARSE_H__

#include <cusparse.h>

/***
cusparseStatus_t
cusparseScsrmm(	cusparseHandle_t			handle,
				cusparseOperation_t			transA,
				int 						m,
				int 						n,
				int 						k,
				int		 					nnz,
				const float*				alpha,
				const cusparseMatDescr_t	descrA,
				const float* 				csrValA,
				const int* 					csrRowPtrA,
				const int* 					csrColIndA,
				const float* 				B,
				int		 					ldb,
				const float*				beta,
				float*						C,
				int		 					ldc
			);

cusparseStatus_t
cusparseDcsrmm(	cusparseHandle_t			handle,
				cusparseOperation_t			transA,
				int							m,
				int							n,
				int							k,
				int							nnz,
				const float*				alpha,
				const cusparseMatDescr_t	descrA,
				const float*				srValA,
				const int*					csrRowPtrA,
				const int*					csrColIndA,
				const float*				B,
				int							ldb,
				const float*				beta,
				float*						C,
				int							ldc
			);
 
***/
cusparseStatus_t
cusparseScsrmm(cusparseHandle_t handle,
 cusparseOperation_t transA,
 int m,
 int n,
 int k,
 int nnz,
 const float *alpha,
 const cusparseMatDescr_t descrA,
 const float *csrValA,
 const int *csrRowPtrA,
 const int *csrColIndA,
 const float *B,
 int ldb,
 const float *beta,
 float *C,
 int ldc);

cusparseStatus_t
cusparseDcsrmm(cusparseHandle_t handle,
 cusparseOperation_t transA,
 int m,
 int n,
 int k,
 int nnz,
 const double *alpha,
 const cusparseMatDescr_t descrA,
 const double *csrValA,
 const int *csrRowPtrA,
 const int *csrColIndA,
 const double *B,
 int ldb,
 const double *beta,
 double *C,
 int ldc);

cusparseStatus_t
cusparseCcsrmm(cusparseHandle_t handle,
 cusparseOperation_t transA,
 int m,
 int n,
 int k,
 int nnz,
 const cuComplex *alpha,
 const cusparseMatDescr_t descrA,
 const cuComplex *csrValA,
 const int *csrRowPtrA,
 const int *csrColIndA,
 const cuComplex *B,
 int ldb,
 const cuComplex *beta,
 cuComplex *C,
 int ldc);

cusparseStatus_t
cusparseScsrmm2(cusparseHandle_t handle,
 cusparseOperation_t transA,
 cusparseOperation_t transB,
 int m,
 int n,
 int k,
 int nnz,
 const float *alpha,
 const cusparseMatDescr_t descrA,
 const float *csrValA,
 const int *csrRowPtrA,
 const int *csrColIndA,
 const float *B,
 int ldb,
 const float *beta,
 float *C,
 int ldc);

cusparseStatus_t
cusparseDcsrmm2(cusparseHandle_t handle,
 cusparseOperation_t transA,
 cusparseOperation_t transB,
 int m,
 int n,
 int k,
 int nnz,
 const double *alpha,
 const cusparseMatDescr_t descrA,
 const double *csrValA,
 const int *csrRowPtrA,
 const int *csrColIndA,
 const double *B,
 int ldb,
 const double *beta,
 double *C,
 int ldc);

cusparseStatus_t
cusparseCcsrmm2(cusparseHandle_t handle,
 cusparseOperation_t transA,
 cusparseOperation_t transB,
 int m,
 int n,
 int k,
 int nnz,
 const cuComplex *alpha,
 const cusparseMatDescr_t descrA,
 const cuComplex *csrValA,
 const int *csrRowPtrA,
 const int *csrColIndA,
 const cuComplex *B,
 int ldb,
 const cuComplex *beta,
 cuComplex *C,
 int ldc);


cusparseStatus_t
cusparseSbsrmm(cusparseHandle_t         handle,
               cusparseDirection_t      dirA,
               cusparseOperation_t      transA,
               cusparseOperation_t      transB,
               int                      mb,
               int                      n,
               int                      kb,
               int                      nnzb,
               const float*             alpha,
               const cusparseMatDescr_t descrA,
               const float*             bsrValA,
               const int*               bsrRowPtrA,
               const int*               bsrColIndA,
               int                      blockDim,
               const float*             B,
               int                      ldb,
               const float*             beta,
               float*                   C,
               int                      ldc);
cusparseStatus_t
cusparseDbsrmm(cusparseHandle_t         handle,
               cusparseDirection_t      dirA,
               cusparseOperation_t      transA,
               cusparseOperation_t      transB,
               int                      mb,
               int                      n,
               int                      kb,
               int                      nnzb,
               const double*            alpha,
               const cusparseMatDescr_t descrA,
               const double*            bsrValA,
               const int*               bsrRowPtrA,
               const int*               bsrColIndA,
               int                      blockDim,
               const double*            B,
               int                      ldb,
               const double*            beta,
               double*                  C,
               int                      ldc);

cusparseStatus_t
cusparseCbsrmm(cusparseHandle_t         handle,
               cusparseDirection_t      dirA,
               cusparseOperation_t      transA,
               cusparseOperation_t      transB,
               int                      mb,
               int                      n,
               int                      kb,
               int                      nnzb,
               const cuComplex*         alpha,
               const cusparseMatDescr_t descrA,
               const cuComplex*         bsrValA,
               const int*               bsrRowPtrA,
               const int*               bsrColIndA,
               int                      blockDim,
               const cuComplex*         B,
               int                      ldb,
               const cuComplex*         beta,
               cuComplex*               C,
               int                      ldc);

cusparseStatus_t
cusparseZbsrmm(cusparseHandle_t         handle,
               cusparseDirection_t      dirA,
               cusparseOperation_t      transA,
               cusparseOperation_t      transB,
               int                      mb,
               int                      n,
               int                      kb,
               int                      nnzb,
               const cuDoubleComplex*   alpha,
               const cusparseMatDescr_t descrA,
               const cuDoubleComplex*   bsrValA,
               const int*               bsrRowPtrA,
               const int*               bsrColIndA,
               int                      blockDim,
               const cuDoubleComplex*   B,
               int                      ldb,
               const cuDoubleComplex*   beta,
               cuDoubleComplex*         C,
               int                      ldc);

#endif
